apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mosquitto

images:
  - name: mosquitto
    newName: docker.io/eclipse-mosquitto
    newTag: 2.0.22-openssl

generatorOptions:
  disableNameSuffixHash: true
  labels:
    type: generated
  annotations:
    note: generated

secretGenerator:
  - name: mosquitto-password
    files:
      - mosquitto-config/password.txt

# patches:
#   - path: service-mqtts-patch.yaml
#   - path: service-mqtt-patch.yaml

resources:
  - ../../base/
  - namespace.yaml
  - persistentVolume.yaml
