apiVersion: v1
kind: PersistentVolume
metadata:
  name: activemq-data
  labels:
    app: activemq
spec:
  capacity:
    storage: 100Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  mountOptions:
  - rw
  - async
  - soft
  - nosuid
  - noatime
  - sec=sys
  - vers=4.0
  - rsize=8192
  - wsize=8192
  - namlen=255
  - timeo=14
  - retrans=2
  - proto=tcp
  - port=0
  nfs:
    server: <server>
    path: <path>
