apiVersion: apps/v1
kind: Deployment
metadata:
  name: mosquitto
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mosquitto
  template:
    metadata:
      labels:
        app: mosquitto
    spec:
      initContainers:
        - name: install
          image: mosquitto
          imagePullPolicy: IfNotPresent
          command: [
              "cp",
              "/mosquitto/tmp/mosquitto.conf",
              "/mosquitto/tmp/password.txt",
              "/mosquitto/config/"
            ]
          volumeMounts:
            - name: workdir
              mountPath: /mosquitto/config/
            - name: config
              mountPath: /mosquitto/tmp/mosquitto.conf
              subPath: mosquitto.conf
            - name: passwords
              mountPath: /mosquitto/tmp/password.txt
              subPath: password.txt
      containers:
        - name: mosquitto
          image: mosquitto
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: 500Mi
              cpu: 200m
            limits:
              memory: 1500Mi
              cpu: 1000m
          ports:
            - name: mqtt
              containerPort: 1883
            - name: mqtts
              containerPort: 8883
            - name: ws
              containerPort: 9001
          volumeMounts:
            - name: workdir
              mountPath: /mosquitto/config/
            - name: certs
              mountPath: /mosquitto/certs/
            - name: data
              mountPath: /mosquitto/data/
      volumes:
        - name: config
          configMap:
            name: mosquitto-config
            defaultMode: 0400
        - name: passwords
          secret:
            secretName: mosquitto-password
            defaultMode: 0400
        - name: certs
          secret:
            secretName: mosquitto-certs
        - name: data
          persistentVolumeClaim:
            claimName: mosquitto-data
        - name: workdir
          emptyDir: {}
